name: 回报错误
description: 告诉我们你遇到的问题
title: '[Bug]: '
labels: [ "bug 🐛" ]

body:
  # User's README and agreement
  - type: markdown
    attributes:
      value: |
        ## 感谢您愿意填写错误回报！
        ## 以下是一些注意事项，请务必阅读让我们能够更容易处理

        ### ❗ | 确定没有相同问题的ISSUE已被提出。
        ### 🌎| 请准确填写环境信息。
        ### ❔ | 打开DEBUG模式复现，并提供出现问题前后至少 10 秒的完整日志内容。请自行删除日志内存在的个人信息及敏感内容。

        ## 如果您不知道如何有效、精准地表述，我们建议您先阅读《提问的智慧》
        链接: [《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
        ---
  - type: checkboxes
    id: terms
    attributes:
      label: 请确保您已阅读以上注意事项，并勾选下方的确认框。
      options:
        - label: "我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。"
          required: true
        - label: "我已经在 [Issue Tracker](https://github.com/luoshuijs/TGPaimonBot/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。"
          required: true
        - label: 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
          required: true
        - label: 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。
          required: true

  # User's data
  - type: markdown
    attributes:
      value: |
        ## 环境信息
        请根据实际使用环境修改以下信息。

  # Env | Version
  - type: input
    id: env-pgm-ver
    attributes:
      label: 程序版本 （Commit Id）
    validations:
      required: true

  # Env | VM Version
  - type: dropdown
    id: env-vm-ver
    attributes:
      label: 运行环境
      description: 选择系统版本
      options:
        - Windows (64)
        - Windows (32/x84)
        - MacOS
        - Linux
        - Ubuntu
        - CentOS
        - ArchLinux
        - UNIX (Android)
        - 其它（请在下方说明）
    validations:
      required: true

  # Env | VM Arch
  - type: dropdown
    id: env-vm-arch
    attributes:
      label: 运行架构
      description: (可选) 选择系统架构
      options:
        - AMD64
        - x86
        - ARM [32] (别名：AArch32 / ARMv7）
        - ARM [64] (别名：AArch64 / ARMv8）
        - 其它

  # Input | Reproduce
  - type: textarea
    id: reproduce-steps
    attributes:
      label: 重现步骤
      description: |
        我们需要执行哪些操作才能让 Bug 出现？
        简洁清晰的重现步骤能够帮助我们更迅速地定位问题所在。
    validations:
      required: true

  # Input | Expected result
  - type: textarea
    id: expected
    attributes:
      label: 期望的结果是什么？
    validations:
      required: true

  # Input | Actual result
  - type: textarea
    id: actual
    attributes:
      label: 实际的结果是什么？
    validations:
      required: true

  # Optional | Reproduce code
  - type: textarea
    id: reproduce-code
    attributes:
      label: 简单的复现代码/链接（可选）
      render: python3

  # Optional | Logging
  - type: textarea
    id: logging
    attributes:
      label: 日志记录（可选）
      render: python3

  # Optional | Extra description
  - type: textarea
    id: extra-desc
    attributes:
      label: 补充说明（可选）
