"""groups_ignore

Revision ID: 369fb74daad9
Revises: cb37027ecae8
Create Date: 2024-03-25 17:29:35.378726

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "369fb74daad9"
down_revision = "cb37027ecae8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("is_ignore", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "is_ignore")
    # ### end Alembic commands ###
