name: test

on:
  push:
    branches:
      - main
    paths:
      - 'tests/**'
  pull_request:
    types: [ opened, synchronize ]
    paths:
      - 'modules/apihelper/**'
      - 'modules/wiki/**'
      - 'tests/**'

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          pip install --upgrade poetry
          poetry config virtualenvs.create false
      - name: Install dependencies
        run: |
          poetry install
          poetry install --extras test
      - name: Test with pytest
        run: |
          python -m pytest